{% set name = "sysloss" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sysloss-{{ version }}.tar.gz
  sha256: 32042df91d1d2fe7e66abd6ca1fe518a33dc1fc4d18be243d895415aadaef51c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10,<4.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.10.0,<4.0.0
    - scipy >=1.9.0,<2.0.0
    - pandas >=2.0.0,<3.0.0
    - rustworkx >=0.13.0
    - rich >=12.0.0
    - toml >=0.10.2
    - matplotlib-base >=3.0.0,<4.0.0
    - tqdm >=4.63.0

test:
  imports:
    - sysloss
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/geddy11/sysloss
  summary: Power analysis of circuits and systems.
  description: |
    sysLoss is a tool for analyzing system power and losses. From the smallest
    IoT sensor to large industrial installations. The tool is efficient and easy
    to use, the analysis result provides a detailed report on voltages, currents,
    power and efficiency for every component defined in the system. sysLoss can
    interface to external battery models to estimate battery life. Output format
    is Pandas DataFrame: Create charts, plots and export to Excel and other formats.
  license: MIT
  license_file: LICENSE
  doc_url: https://sysloss.readthedocs.io/
  dev_url: https://github.com/geddy11/sysloss


extra:
  recipe-maintainers:
    - geddy11
