{% set name = "sysloss" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sysloss-{{ version }}.tar.gz
  sha256: 35c72b187ecca74a2222af53a70ffe7d6674375f6ff3baf192586014c2a3eedd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10,<4.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.10.0,<4.0.0
    - scipy >=1.9.0,<2.0.0
    - pandas >=2.0.0,<3.0.0
    - rustworkx >=0.13.0,<0.14.0
    - rich >=12.0.0,<13.0.0
    - toml >=0.10.2,<0.11.0
    - matplotlib-base >=3.0.0,<4.0.0

test:
  imports:
    - sysloss
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/geddy11/sysloss
  summary: Power analysis of circuits and systems.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - geddy11
