{% set name = "sysloss" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sysloss-{{ version }}.tar.gz
  sha256: 14bfa5abe6d4524156390a99e52e655b0a79f24b93b69394b4d8b1be5b3086f3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10,<4.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.10.0,<4.0.0
    - scipy >=1.9.0,<2.0.0
    - pandas >=2.0.0,<3.0.0
    - rustworkx >=0.13.0
    - rich >=12.0.0
    - toml >=0.10.2
    - matplotlib-base >=3.0.0,<4.0.0
    - tqdm >=4.63.0
    - packaging >=21.1
    - pydot >=3.0.0
    - pillow >=9.3.0

test:
  imports:
    - sysloss
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/geddy11/sysloss
  summary: Power tree analysis of circuits, boards and systems.
  description: |
    sysLoss is a tool for analyzing power trees in systems, boards and circuits - 
    from the smallest IoT sensor to large industrial installations. The tool is 
    efficient and easy to use, the analysis result provides a detailed report on 
    voltages, currents, power, loss and efficiency for every component defined 
    in the system. sysLoss can interface to external battery models to estimate 
    battery life. Output format is Pandas DataFrame: Create charts, plots and 
    export to Excel and other formats. sysLoss can also produce graphical power 
    tree diagrams in a wide range of image formats.
  license: MIT
  license_file: LICENSE
  doc_url: https://sysloss.readthedocs.io/
  dev_url: https://github.com/geddy11/sysloss


extra:
  recipe-maintainers:
    - geddy11
